def build_todo_help_text() -> str:
    return (
        "<b>Todos bot — help</b>\n\n"
        "<b>Link account</b>\n"
        "Day Planner → Todos → Settings → Connect Todo Telegram → "
        "tap <b>Start</b> in this chat.\n\n"
        "<b>Commands</b>\n"
        "/start — welcome & link instructions\n"
        "/help — this message\n"
        "/today — today's task list (image)\n"
        "/create — add a new task (step by step)\n"
        "/cancel — stop /create mid-flow\n"
        "/link &lt;code&gt; — link with 6-digit code\n\n"
        "<b>Automatic notifications</b>\n"
        "• ~5 AM — yesterday's summary (Done/Skip buttons, 7 days)\n"
        "• ~5 AM — today's tasks (no buttons)\n"
        "• 15 min before each task — reminder with buttons\n"
        "• End of task window — reminder with buttons\n\n"
        "<b>Quick actions on notifications</b>\n"
        "Tap <b>Done</b> / <b>Skip</b> / <b>Postpone</b> buttons.\n"
        "Postpone → quick presets or <b>Custom</b> (calendar + time picker).\n"
        "You can also reply:\n"
        "<code>2 yes</code> — mark task 2 done\n"
        "<code>2 no</code> — mark task 2 skipped\n\n"
        "<b>/create formats</b>\n"
        "• Date & time: <code>DD-MM-YYYY HH:MM</code>\n"
        "  e.g. <code>07-07-2026 09:30</code>\n"
        "• Or: <code>today 09:30</code> / <code>tomorrow 14:00</code>\n"
        "• Repeat until: <code>DD-MM-YYYY</code>\n"
        "• Custom days: <code>mon,wed,fri</code> or <code>0,2,4</code>\n"
        "  (0=Mon … 6=Sun)\n\n"
        "<b>Repeat options</b>\n"
        "1 One time · 2 Daily · 3 Weekly · 4 Weekdays\n"
        "5 Monthly · 6 Custom days"
    )
